openapi: 3.0.3
info:
    title: XSFC Resource Operator API
    description: REST API for listing providers, consumers, injections, accounts, modules and monitored types.
    version: 0.1.0
servers:
    - url: http://localhost:8088
paths:
    /accounts:
        get:
            tags:
                - inventory
            summary: accounts inventory
            operationId: inventory#accounts
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/XsfcAccount'
                                example:
                                    - consumerName: Commodi pariatur et sint accusantium suscipit eum.
                                      consumerNamespace: Consequatur omnis impedit dolor nam vel voluptates.
                                      createdBy: Eum voluptas in inventore.
                                      name: Accusantium esse omnis alias.
                                      namespace: Omnis laudantium eaque nobis molestiae animi.
                                      providerName: Quae quas et rerum laboriosam.
                                      providerNamespace: Sit est et saepe corporis id delectus.
                                      type: Nam similique delectus quae eius.
                                    - consumerName: Commodi pariatur et sint accusantium suscipit eum.
                                      consumerNamespace: Consequatur omnis impedit dolor nam vel voluptates.
                                      createdBy: Eum voluptas in inventore.
                                      name: Accusantium esse omnis alias.
                                      namespace: Omnis laudantium eaque nobis molestiae animi.
                                      providerName: Quae quas et rerum laboriosam.
                                      providerNamespace: Sit est et saepe corporis id delectus.
                                      type: Nam similique delectus quae eius.
                                    - consumerName: Commodi pariatur et sint accusantium suscipit eum.
                                      consumerNamespace: Consequatur omnis impedit dolor nam vel voluptates.
                                      createdBy: Eum voluptas in inventore.
                                      name: Accusantium esse omnis alias.
                                      namespace: Omnis laudantium eaque nobis molestiae animi.
                                      providerName: Quae quas et rerum laboriosam.
                                      providerNamespace: Sit est et saepe corporis id delectus.
                                      type: Nam similique delectus quae eius.
                            example:
                                - consumerName: Commodi pariatur et sint accusantium suscipit eum.
                                  consumerNamespace: Consequatur omnis impedit dolor nam vel voluptates.
                                  createdBy: Eum voluptas in inventore.
                                  name: Accusantium esse omnis alias.
                                  namespace: Omnis laudantium eaque nobis molestiae animi.
                                  providerName: Quae quas et rerum laboriosam.
                                  providerNamespace: Sit est et saepe corporis id delectus.
                                  type: Nam similique delectus quae eius.
                                - consumerName: Commodi pariatur et sint accusantium suscipit eum.
                                  consumerNamespace: Consequatur omnis impedit dolor nam vel voluptates.
                                  createdBy: Eum voluptas in inventore.
                                  name: Accusantium esse omnis alias.
                                  namespace: Omnis laudantium eaque nobis molestiae animi.
                                  providerName: Quae quas et rerum laboriosam.
                                  providerNamespace: Sit est et saepe corporis id delectus.
                                  type: Nam similique delectus quae eius.
    /accounts/by-consumer/{namespace}/{name}:
        get:
            tags:
                - inventory
            summary: accountsByConsumer inventory
            operationId: inventory#accountsByConsumer
            parameters:
                - name: namespace
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Sed consequatur est.
                  example: Praesentium expedita magnam aut voluptates fugiat.
                - name: name
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Quo nihil.
                  example: Maxime rerum nulla suscipit adipisci.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/XsfcAccount'
                                example:
                                    - consumerName: Commodi pariatur et sint accusantium suscipit eum.
                                      consumerNamespace: Consequatur omnis impedit dolor nam vel voluptates.
                                      createdBy: Eum voluptas in inventore.
                                      name: Accusantium esse omnis alias.
                                      namespace: Omnis laudantium eaque nobis molestiae animi.
                                      providerName: Quae quas et rerum laboriosam.
                                      providerNamespace: Sit est et saepe corporis id delectus.
                                      type: Nam similique delectus quae eius.
                                    - consumerName: Commodi pariatur et sint accusantium suscipit eum.
                                      consumerNamespace: Consequatur omnis impedit dolor nam vel voluptates.
                                      createdBy: Eum voluptas in inventore.
                                      name: Accusantium esse omnis alias.
                                      namespace: Omnis laudantium eaque nobis molestiae animi.
                                      providerName: Quae quas et rerum laboriosam.
                                      providerNamespace: Sit est et saepe corporis id delectus.
                                      type: Nam similique delectus quae eius.
                                    - consumerName: Commodi pariatur et sint accusantium suscipit eum.
                                      consumerNamespace: Consequatur omnis impedit dolor nam vel voluptates.
                                      createdBy: Eum voluptas in inventore.
                                      name: Accusantium esse omnis alias.
                                      namespace: Omnis laudantium eaque nobis molestiae animi.
                                      providerName: Quae quas et rerum laboriosam.
                                      providerNamespace: Sit est et saepe corporis id delectus.
                                      type: Nam similique delectus quae eius.
                                    - consumerName: Commodi pariatur et sint accusantium suscipit eum.
                                      consumerNamespace: Consequatur omnis impedit dolor nam vel voluptates.
                                      createdBy: Eum voluptas in inventore.
                                      name: Accusantium esse omnis alias.
                                      namespace: Omnis laudantium eaque nobis molestiae animi.
                                      providerName: Quae quas et rerum laboriosam.
                                      providerNamespace: Sit est et saepe corporis id delectus.
                                      type: Nam similique delectus quae eius.
                            example:
                                - consumerName: Commodi pariatur et sint accusantium suscipit eum.
                                  consumerNamespace: Consequatur omnis impedit dolor nam vel voluptates.
                                  createdBy: Eum voluptas in inventore.
                                  name: Accusantium esse omnis alias.
                                  namespace: Omnis laudantium eaque nobis molestiae animi.
                                  providerName: Quae quas et rerum laboriosam.
                                  providerNamespace: Sit est et saepe corporis id delectus.
                                  type: Nam similique delectus quae eius.
                                - consumerName: Commodi pariatur et sint accusantium suscipit eum.
                                  consumerNamespace: Consequatur omnis impedit dolor nam vel voluptates.
                                  createdBy: Eum voluptas in inventore.
                                  name: Accusantium esse omnis alias.
                                  namespace: Omnis laudantium eaque nobis molestiae animi.
                                  providerName: Quae quas et rerum laboriosam.
                                  providerNamespace: Sit est et saepe corporis id delectus.
                                  type: Nam similique delectus quae eius.
    /consumers:
        get:
            tags:
                - inventory
            summary: consumers inventory
            operationId: inventory#consumers
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/XsfcConsumer'
                                example:
                                    - kind: Quo reprehenderit optio harum.
                                      name: Voluptate debitis.
                                      namespace: Sit mollitia eius.
                                      requestedTypes:
                                        - Aperiam animi quisquam voluptatem.
                                        - Asperiores occaecati mollitia commodi dolore commodi.
                                        - Dolorum reprehenderit maiores vero est consequatur.
                                        - Numquam id vero.
                                      resource: Minus dolorem quae molestiae sit.
                                      type: Omnis non at id eos accusamus.
                                    - kind: Quo reprehenderit optio harum.
                                      name: Voluptate debitis.
                                      namespace: Sit mollitia eius.
                                      requestedTypes:
                                        - Aperiam animi quisquam voluptatem.
                                        - Asperiores occaecati mollitia commodi dolore commodi.
                                        - Dolorum reprehenderit maiores vero est consequatur.
                                        - Numquam id vero.
                                      resource: Minus dolorem quae molestiae sit.
                                      type: Omnis non at id eos accusamus.
                                    - kind: Quo reprehenderit optio harum.
                                      name: Voluptate debitis.
                                      namespace: Sit mollitia eius.
                                      requestedTypes:
                                        - Aperiam animi quisquam voluptatem.
                                        - Asperiores occaecati mollitia commodi dolore commodi.
                                        - Dolorum reprehenderit maiores vero est consequatur.
                                        - Numquam id vero.
                                      resource: Minus dolorem quae molestiae sit.
                                      type: Omnis non at id eos accusamus.
                                    - kind: Quo reprehenderit optio harum.
                                      name: Voluptate debitis.
                                      namespace: Sit mollitia eius.
                                      requestedTypes:
                                        - Aperiam animi quisquam voluptatem.
                                        - Asperiores occaecati mollitia commodi dolore commodi.
                                        - Dolorum reprehenderit maiores vero est consequatur.
                                        - Numquam id vero.
                                      resource: Minus dolorem quae molestiae sit.
                                      type: Omnis non at id eos accusamus.
                            example:
                                - kind: Quo reprehenderit optio harum.
                                  name: Voluptate debitis.
                                  namespace: Sit mollitia eius.
                                  requestedTypes:
                                    - Aperiam animi quisquam voluptatem.
                                    - Asperiores occaecati mollitia commodi dolore commodi.
                                    - Dolorum reprehenderit maiores vero est consequatur.
                                    - Numquam id vero.
                                  resource: Minus dolorem quae molestiae sit.
                                  type: Omnis non at id eos accusamus.
                                - kind: Quo reprehenderit optio harum.
                                  name: Voluptate debitis.
                                  namespace: Sit mollitia eius.
                                  requestedTypes:
                                    - Aperiam animi quisquam voluptatem.
                                    - Asperiores occaecati mollitia commodi dolore commodi.
                                    - Dolorum reprehenderit maiores vero est consequatur.
                                    - Numquam id vero.
                                  resource: Minus dolorem quae molestiae sit.
                                  type: Omnis non at id eos accusamus.
    /healthz:
        get:
            tags:
                - inventory
            summary: healthz inventory
            operationId: inventory#healthz
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Sint neque expedita voluptas dolor cupiditate autem.
                            example: Voluptatum qui quasi quas illo incidunt inventore.
    /injections:
        get:
            tags:
                - inventory
            summary: injections inventory
            operationId: inventory#injections
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/XsfcInjection'
                                example:
                                    - consumerKind: Rerum et veniam dignissimos nemo.
                                      consumerName: Praesentium velit eligendi eum aspernatur fugit.
                                      consumerNamespace: Et ut.
                                      container: Eligendi pariatur sunt dicta fugit et consectetur.
                                      mode: Dolores consequuntur sed sunt odio alias.
                                      requestedTypes:
                                        - Libero ab in qui magnam sint ut.
                                        - Minus molestiae.
                                      sourceManifest: Vero atque cum necessitatibus.
                                      status: Eos sit eligendi ea nihil quis cumque.
                                    - consumerKind: Rerum et veniam dignissimos nemo.
                                      consumerName: Praesentium velit eligendi eum aspernatur fugit.
                                      consumerNamespace: Et ut.
                                      container: Eligendi pariatur sunt dicta fugit et consectetur.
                                      mode: Dolores consequuntur sed sunt odio alias.
                                      requestedTypes:
                                        - Libero ab in qui magnam sint ut.
                                        - Minus molestiae.
                                      sourceManifest: Vero atque cum necessitatibus.
                                      status: Eos sit eligendi ea nihil quis cumque.
                                    - consumerKind: Rerum et veniam dignissimos nemo.
                                      consumerName: Praesentium velit eligendi eum aspernatur fugit.
                                      consumerNamespace: Et ut.
                                      container: Eligendi pariatur sunt dicta fugit et consectetur.
                                      mode: Dolores consequuntur sed sunt odio alias.
                                      requestedTypes:
                                        - Libero ab in qui magnam sint ut.
                                        - Minus molestiae.
                                      sourceManifest: Vero atque cum necessitatibus.
                                      status: Eos sit eligendi ea nihil quis cumque.
                            example:
                                - consumerKind: Rerum et veniam dignissimos nemo.
                                  consumerName: Praesentium velit eligendi eum aspernatur fugit.
                                  consumerNamespace: Et ut.
                                  container: Eligendi pariatur sunt dicta fugit et consectetur.
                                  mode: Dolores consequuntur sed sunt odio alias.
                                  requestedTypes:
                                    - Libero ab in qui magnam sint ut.
                                    - Minus molestiae.
                                  sourceManifest: Vero atque cum necessitatibus.
                                  status: Eos sit eligendi ea nihil quis cumque.
                                - consumerKind: Rerum et veniam dignissimos nemo.
                                  consumerName: Praesentium velit eligendi eum aspernatur fugit.
                                  consumerNamespace: Et ut.
                                  container: Eligendi pariatur sunt dicta fugit et consectetur.
                                  mode: Dolores consequuntur sed sunt odio alias.
                                  requestedTypes:
                                    - Libero ab in qui magnam sint ut.
                                    - Minus molestiae.
                                  sourceManifest: Vero atque cum necessitatibus.
                                  status: Eos sit eligendi ea nihil quis cumque.
    /manifests/requesting-injection:
        get:
            tags:
                - inventory
            summary: manifestsRequestingInjection inventory
            operationId: inventory#manifestsRequestingInjection
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/XsfcManifest'
                                example:
                                    - annotations:
                                        Accusantium est.: Sit ad.
                                      apiVersion: Voluptates dignissimos quos mollitia veritatis sed.
                                      kind: Velit iure nostrum recusandae inventore et sed.
                                      labels:
                                        Laboriosam inventore ut consectetur.: Sunt aliquam.
                                      name: Recusandae et.
                                      namespace: Harum officia minus.
                                      requestedTypes:
                                        - Animi sed veniam enim at qui recusandae.
                                        - Nemo eius et et vel itaque.
                                        - Eum nisi similique ex perspiciatis nesciunt ipsam.
                                    - annotations:
                                        Accusantium est.: Sit ad.
                                      apiVersion: Voluptates dignissimos quos mollitia veritatis sed.
                                      kind: Velit iure nostrum recusandae inventore et sed.
                                      labels:
                                        Laboriosam inventore ut consectetur.: Sunt aliquam.
                                      name: Recusandae et.
                                      namespace: Harum officia minus.
                                      requestedTypes:
                                        - Animi sed veniam enim at qui recusandae.
                                        - Nemo eius et et vel itaque.
                                        - Eum nisi similique ex perspiciatis nesciunt ipsam.
                            example:
                                - annotations:
                                    Accusantium est.: Sit ad.
                                  apiVersion: Voluptates dignissimos quos mollitia veritatis sed.
                                  kind: Velit iure nostrum recusandae inventore et sed.
                                  labels:
                                    Laboriosam inventore ut consectetur.: Sunt aliquam.
                                  name: Recusandae et.
                                  namespace: Harum officia minus.
                                  requestedTypes:
                                    - Animi sed veniam enim at qui recusandae.
                                    - Nemo eius et et vel itaque.
                                    - Eum nisi similique ex perspiciatis nesciunt ipsam.
                                - annotations:
                                    Accusantium est.: Sit ad.
                                  apiVersion: Voluptates dignissimos quos mollitia veritatis sed.
                                  kind: Velit iure nostrum recusandae inventore et sed.
                                  labels:
                                    Laboriosam inventore ut consectetur.: Sunt aliquam.
                                  name: Recusandae et.
                                  namespace: Harum officia minus.
                                  requestedTypes:
                                    - Animi sed veniam enim at qui recusandae.
                                    - Nemo eius et et vel itaque.
                                    - Eum nisi similique ex perspiciatis nesciunt ipsam.
    /modules:
        get:
            tags:
                - inventory
            summary: modules inventory
            operationId: inventory#modules
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/XsfcModule'
                                example:
                                    - capabilities:
                                        - Rerum illum.
                                        - Nostrum est.
                                      name: Necessitatibus quia iure rerum.
                                      types:
                                        - Eos sit.
                                        - Optio earum.
                                        - Mollitia molestiae sit voluptas modi.
                                        - Est ullam molestiae quos fugit ut enim.
                                      version: Officiis occaecati aut.
                                    - capabilities:
                                        - Rerum illum.
                                        - Nostrum est.
                                      name: Necessitatibus quia iure rerum.
                                      types:
                                        - Eos sit.
                                        - Optio earum.
                                        - Mollitia molestiae sit voluptas modi.
                                        - Est ullam molestiae quos fugit ut enim.
                                      version: Officiis occaecati aut.
                                    - capabilities:
                                        - Rerum illum.
                                        - Nostrum est.
                                      name: Necessitatibus quia iure rerum.
                                      types:
                                        - Eos sit.
                                        - Optio earum.
                                        - Mollitia molestiae sit voluptas modi.
                                        - Est ullam molestiae quos fugit ut enim.
                                      version: Officiis occaecati aut.
                            example:
                                - capabilities:
                                    - Rerum illum.
                                    - Nostrum est.
                                  name: Necessitatibus quia iure rerum.
                                  types:
                                    - Eos sit.
                                    - Optio earum.
                                    - Mollitia molestiae sit voluptas modi.
                                    - Est ullam molestiae quos fugit ut enim.
                                  version: Officiis occaecati aut.
                                - capabilities:
                                    - Rerum illum.
                                    - Nostrum est.
                                  name: Necessitatibus quia iure rerum.
                                  types:
                                    - Eos sit.
                                    - Optio earum.
                                    - Mollitia molestiae sit voluptas modi.
                                    - Est ullam molestiae quos fugit ut enim.
                                  version: Officiis occaecati aut.
    /providers:
        get:
            tags:
                - inventory
            summary: providers inventory
            operationId: inventory#providers
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/XsfcProvider'
                                example:
                                    - kind: Delectus porro sunt et aliquid tempora.
                                      module: Illum eius velit aspernatur reiciendis eveniet.
                                      name: Cumque sint mollitia ipsam rem a aperiam.
                                      namespace: Et vero soluta adipisci sit vitae magnam.
                                      resource: Excepturi eos sit.
                                      type: Ut similique.
                                    - kind: Delectus porro sunt et aliquid tempora.
                                      module: Illum eius velit aspernatur reiciendis eveniet.
                                      name: Cumque sint mollitia ipsam rem a aperiam.
                                      namespace: Et vero soluta adipisci sit vitae magnam.
                                      resource: Excepturi eos sit.
                                      type: Ut similique.
                            example:
                                - kind: Delectus porro sunt et aliquid tempora.
                                  module: Illum eius velit aspernatur reiciendis eveniet.
                                  name: Cumque sint mollitia ipsam rem a aperiam.
                                  namespace: Et vero soluta adipisci sit vitae magnam.
                                  resource: Excepturi eos sit.
                                  type: Ut similique.
                                - kind: Delectus porro sunt et aliquid tempora.
                                  module: Illum eius velit aspernatur reiciendis eveniet.
                                  name: Cumque sint mollitia ipsam rem a aperiam.
                                  namespace: Et vero soluta adipisci sit vitae magnam.
                                  resource: Excepturi eos sit.
                                  type: Ut similique.
                                - kind: Delectus porro sunt et aliquid tempora.
                                  module: Illum eius velit aspernatur reiciendis eveniet.
                                  name: Cumque sint mollitia ipsam rem a aperiam.
                                  namespace: Et vero soluta adipisci sit vitae magnam.
                                  resource: Excepturi eos sit.
                                  type: Ut similique.
                                - kind: Delectus porro sunt et aliquid tempora.
                                  module: Illum eius velit aspernatur reiciendis eveniet.
                                  name: Cumque sint mollitia ipsam rem a aperiam.
                                  namespace: Et vero soluta adipisci sit vitae magnam.
                                  resource: Excepturi eos sit.
                                  type: Ut similique.
    /readyz:
        get:
            tags:
                - inventory
            summary: readyz inventory
            operationId: inventory#readyz
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Id ipsum.
                            example: Earum hic et.
    /types:
        get:
            tags:
                - inventory
            summary: types inventory
            operationId: inventory#types
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                                    example: Aut laborum nesciunt.
                                example:
                                    - Id omnis cum.
                                    - Fugit porro recusandae vel.
                                    - Consequuntur aut enim.
                                    - Nostrum soluta.
                            example:
                                - Similique eaque dolorem ea hic aut est.
                                - Praesentium nihil temporibus ducimus qui rerum harum.
                                - Ut dignissimos.
    /version:
        get:
            tags:
                - inventory
            summary: version inventory
            operationId: inventory#version
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/XsfcVersion'
                            example:
                                buildDate: Quo delectus et eos sed.
                                gitCommit: Pariatur vel incidunt id maxime mollitia.
                                operatorVersion: Quos non saepe excepturi nemo nulla.
components:
    schemas:
        XsfcAccount:
            type: object
            properties:
                consumerName:
                    type: string
                    example: Sunt laboriosam eius doloremque enim quam vero.
                consumerNamespace:
                    type: string
                    example: Maxime repudiandae.
                createdBy:
                    type: string
                    example: Ea quisquam quaerat laudantium nemo eligendi harum.
                name:
                    type: string
                    example: Atque iste odit fugiat.
                namespace:
                    type: string
                    example: Quia sunt repellendus ab rerum.
                providerName:
                    type: string
                    example: Eveniet repellendus est totam exercitationem alias eveniet.
                providerNamespace:
                    type: string
                    example: Architecto unde eos.
                type:
                    type: string
                    example: Modi repellat enim.
            example:
                consumerName: Est et numquam qui iste.
                consumerNamespace: Quaerat incidunt dolor autem.
                createdBy: Optio error voluptatem qui.
                name: Itaque rerum sunt vero dolores.
                namespace: Voluptates suscipit.
                providerName: Consectetur officiis eaque explicabo incidunt.
                providerNamespace: Impedit sint.
                type: Totam eaque in voluptas quae in consectetur.
        XsfcConsumer:
            type: object
            properties:
                kind:
                    type: string
                    example: Sint eum corrupti fugiat et.
                name:
                    type: string
                    example: Est molestiae.
                namespace:
                    type: string
                    example: Vel temporibus voluptatem molestiae doloribus.
                requestedTypes:
                    type: array
                    items:
                        type: string
                        example: Nihil fuga voluptas laborum consequatur dolor.
                    example:
                        - Nulla facilis.
                        - Magni vitae sit sed.
                        - Magni repudiandae nobis perspiciatis.
                        - Et iusto et.
                resource:
                    type: string
                    example: Culpa et eum eius quis.
                type:
                    type: string
                    example: Nisi aut.
            example:
                kind: Et distinctio in alias eveniet.
                name: Perspiciatis sunt expedita.
                namespace: Eius est perferendis laboriosam quisquam earum.
                requestedTypes:
                    - Sint in eum atque.
                    - Sapiente a et reprehenderit.
                    - Dolorem temporibus necessitatibus corrupti perferendis qui.
                    - Tempora minima quam voluptas voluptatem.
                resource: Voluptate qui quo modi atque.
                type: Suscipit vero dolorum.
        XsfcInjection:
            type: object
            properties:
                consumerKind:
                    type: string
                    example: Nesciunt dolorum veritatis voluptas aut.
                consumerName:
                    type: string
                    example: Est aliquid.
                consumerNamespace:
                    type: string
                    example: Id a neque.
                container:
                    type: string
                    example: Iusto quia consectetur.
                mode:
                    type: string
                    example: Quia aliquid excepturi quia nihil delectus qui.
                requestedTypes:
                    type: array
                    items:
                        type: string
                        example: Corrupti assumenda perspiciatis occaecati sint aliquid.
                    example:
                        - Omnis autem tempora.
                        - Veniam blanditiis id id.
                        - Dolorum et dolorum est non.
                        - Voluptatum maiores.
                sourceManifest:
                    type: string
                    example: Autem et rerum harum beatae ut.
                status:
                    type: string
                    example: Hic est velit occaecati.
            example:
                consumerKind: Itaque debitis.
                consumerName: Quis quia.
                consumerNamespace: Et nobis eaque.
                container: Quia quam provident.
                mode: Libero tempore ut nihil quis beatae.
                requestedTypes:
                    - Nam modi explicabo.
                    - Ut sit facilis aut expedita.
                sourceManifest: Excepturi distinctio labore non nesciunt.
                status: Eveniet aspernatur numquam amet voluptas.
        XsfcManifest:
            type: object
            properties:
                annotations:
                    type: object
                    example:
                        Dolor id illum recusandae nesciunt adipisci qui.: Quas fuga perspiciatis vitae reprehenderit quos voluptatem.
                        Tempora veritatis tempora sequi itaque consequatur.: Est dolores.
                    additionalProperties:
                        type: string
                        example: Id unde sequi.
                apiVersion:
                    type: string
                    example: Repudiandae quisquam.
                kind:
                    type: string
                    example: Ut et assumenda.
                labels:
                    type: object
                    example:
                        Cum temporibus.: Velit blanditiis optio quia quam minima.
                        Omnis ut illo.: Eum officia hic et in qui sequi.
                        Ut corrupti maxime et voluptas ratione.: Consequatur architecto.
                    additionalProperties:
                        type: string
                        example: Maxime officiis id earum nemo consequatur temporibus.
                name:
                    type: string
                    example: Autem voluptas rem explicabo corrupti.
                namespace:
                    type: string
                    example: Consectetur veritatis voluptate fugiat repudiandae assumenda quibusdam.
                requestedTypes:
                    type: array
                    items:
                        type: string
                        example: Molestiae quos ea eius amet.
                    example:
                        - Laborum nobis deserunt.
                        - Quia non consectetur animi molestias culpa aut.
                        - Sit totam sint tempora rem officiis.
            example:
                annotations:
                    Et quibusdam aut.: Nesciunt assumenda atque totam quae illum.
                apiVersion: Et occaecati dolorum est voluptatem maiores.
                kind: Tenetur et ut eum et molestiae harum.
                labels:
                    Est est eius alias hic pariatur.: Reprehenderit non facilis sunt ut et.
                    Ipsa ex est occaecati necessitatibus.: Tenetur vitae minus veniam.
                    Voluptatem dolores repudiandae asperiores omnis dolores ut.: Tenetur dolorum ab.
                name: Rerum soluta.
                namespace: Voluptas quis at amet aliquam.
                requestedTypes:
                    - Adipisci blanditiis vero quam nihil.
                    - Et accusantium sapiente est voluptatem natus.
                    - Totam asperiores.
                    - Omnis eveniet quia laboriosam.
        XsfcModule:
            type: object
            properties:
                capabilities:
                    type: array
                    items:
                        type: string
                        example: Non necessitatibus hic et amet.
                    example:
                        - Nulla aliquid id soluta.
                        - Modi animi et.
                        - Numquam consectetur veniam distinctio provident ab.
                        - Iure commodi minima harum qui repellendus.
                name:
                    type: string
                    example: Vitae id sint.
                types:
                    type: array
                    items:
                        type: string
                        example: Est et eveniet tenetur sed quo.
                    example:
                        - Nobis sed in ducimus.
                        - Fugit adipisci.
                version:
                    type: string
                    example: Atque optio at et consectetur dolores.
            example:
                capabilities:
                    - Est non in quos est ipsum et.
                    - Corrupti ipsum magnam et voluptatum aut quod.
                    - Iusto quaerat.
                    - Voluptatem voluptatem.
                name: Molestiae qui distinctio qui qui reprehenderit.
                types:
                    - Excepturi explicabo ut.
                    - Porro eveniet dolorum totam laudantium.
                    - Rerum dolor dolor.
                version: Tempore ratione.
        XsfcProvider:
            type: object
            properties:
                kind:
                    type: string
                    example: Repellat in.
                module:
                    type: string
                    example: Ad aliquam.
                name:
                    type: string
                    example: Debitis enim et.
                namespace:
                    type: string
                    example: Libero et qui dolores.
                resource:
                    type: string
                    example: Cum voluptatum perferendis est quasi eaque cupiditate.
                type:
                    type: string
                    example: Tempora tempora consequatur.
            example:
                kind: Eaque quo quos sunt cumque rerum omnis.
                module: Architecto ad ipsa ut est culpa.
                name: Sunt mollitia.
                namespace: Iusto mollitia iure nemo.
                resource: Aut asperiores voluptatem ex pariatur consectetur.
                type: Quibusdam autem tenetur voluptatum.
        XsfcVersion:
            type: object
            properties:
                buildDate:
                    type: string
                    example: Atque consequatur.
                gitCommit:
                    type: string
                    example: Quaerat aut illum et fugiat aspernatur autem.
                operatorVersion:
                    type: string
                    example: Reiciendis facilis.
            example:
                buildDate: Non dolorem in excepturi beatae hic.
                gitCommit: Esse sed possimus.
                operatorVersion: Exercitationem excepturi et.
tags:
    - name: inventory
